services:
  registory_auth:
    image: docker_auth
    restart: always
    volumes:
      - ./docker_auth/config:/config:ro
      - ./logs:/logs
      - ./certs:/certs
    ports:
      - "5001:5001"
    env_file:
      - auth.env
    networks:
      - registory_nw

  registory_core:
    image: registry:2
    volumes:
      - ./certs:/certs
      - ./data:/var/lib/registry
    restart: always
    ports:
      - 7443:443
    env_file:
      - repository.env
    networks:
      - registory_nw
    depends_on:
      - registory_auth

networks:
  registory_nw:
